//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Id_friend { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_user_friend { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
