//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id_message { get; set; }
        public Nullable<int> Id_send_user { get; set; }
        public Nullable<int> Id_recv_user { get; set; }
        public string message1 { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
