//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id_score { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_place { get; set; }
        public Nullable<int> visited { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
    }
}
